language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
dist: trusty

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  - PEP8_IGNORE="E221,E501,W504"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage pep8 nose

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
  - export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
  - coverage run --source=params_flow $(which nosetests) --with-doctest tests/
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then coverage report --show-missing --fail-under=100; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pep8 --ignore=$PEP8_IGNORE  --exclude=tests,.venv -r --show-source . ; fi
  # For convenience, make sure simple test commands work
  - python setup.py develop
  - py.test
  - nosetests
# load coverage status to https://coveralls.io
after_success:
  - 'echo travis-python: $TRAVIS_PYTHON_VERSION'
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install coveralls; COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls ; fi

notifications:
  email: false
  
deploy:
  provider: pypi
  username: kpe
  password:
    secure: e5wV98e/MPIZV9kRfXVkmmNwvEJRzDsKAFxSlfkpOI9BqI2aBN4IBrekpn0LwCrIQ4mbUYXd8FOc5BMBqISzwdHC2azKtRk+XDQI3vc6XpHwW7m/HLXTL1mrVQ3rumJnbk+1fitplvJhGCY46zNy+D6FQzWhpThA0Q3T1F9mVsLtZblmwLi450NrnXiqLEGjM4CbK8ROvbd1G8PrlpNwHQW9/TgoMBE0PQc5vKU3TlzvbdqahVoaDg0o3cFISfXk7JKmNrA49kkKoaFBzcatqUy2DXoaOx43++4yuRnE0m9juL7tJSBJYnzGrih14zuU+kKBUCLM5ty7b5s4r2+LvQZpWy+WuTKG+9CqSPtiLlBlULHQNdH6j50qpIW5kJd+UhBRB+1KrpXC73DvWErXxpk0X9FIdAlw+sIxQMxWX7xLXyk88Gsh8m5WKxNwV/19fL3DiHHfD37R56wvvr5A0IU2VXTyLwy4HWIiCy9exwezOv3T+Gjsne0/i7vsoQXp9Nohf5T5lKANEP7EcWs+s1anFiZgYJgzCA7Wa9ppCR0WK98MWPRnaJ3kMZn5XyLkwl8+DTKbT+HfYZWBvAnlf18Kv6C2z7BYvqQNroH6VNurxscfS1mrM4+vNEcYz1yJo6yxRHWmxYqoue5e3bn1EltUxRClcyVBpr6LKxdbk8k=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  skip_existing: true
